### ISSUE TITLE
Bucketeer's Sprite Dump (initial)

### ISSUE THREAD

**Issue by GeneralWadaling** [yairm210/Unciv-Tilesets#1]
[Bucketeers Super Uber Ultra Sprite Dumper Collection Ver1.zip](https://github.com/user-attachments/files/16470358/Bucketeers.Super.Uber.Ultra.Sprite.Dumper.Collection.Ver1.zip)

So here's my initial dump of sprites that are (mostly) not default tileset items and currently in my stash.

Contents:
- Arcane & Diesel unit sprite pack from my scrapped dieselpunk x fantasy genre mod idea FantasiAlpha
- Sprite contributed by me to the Advanced Wars mod
- Extra tile sprites of both tilesets, containing mostly requested sprites made for other modders.
  - FantasyHex extra tile sprites also contains some of my old attempts of different city center styles, and more recently the district prototypes.
- My sprites used for Unit Style Set.
- My sprites used for Warfare Expanded.
- Sprite sheet of building components, for TC and districts, from Ancient up to Medieval. Medieval is not complete yet, but it should satisfy needs of some modders.
  - Notes: If you need to use those components from the sprite sheets, the modders may need image editing apps (Microsoft Paint would suffice) to extract the image manually.
- Victory banners I made very long ago.

Feel free to reorganize them in the way you want! (:P)

**Comment by yairm210** [comment]
Sprite sheets and victory banners we don't really have a place to add, all the rest added :)
